### ISSUE TITLE
Upgrading from 0.1.12 to 0.1.14

### ISSUE THREAD

**Issue by PierrotGIT** [lorensr/segmented-control#39]
Hi there, we are using this module in our project, it was working fine until this morning with that error during the ReactJS project build : 
Cannot find module: 'segmented-control'. Make sure this package is installed.
You can install this package by running: npm install segmented-control.

The version looked Deprecated, so we decided to upgrade to 0.1.14.

The install looks fine but the error still the same during the build :
Cannot find module: 'segmented-control'. Make sure this package is installed.
You can install this package by running: npm install segmented-control.

We use it in 1 page only with this import : 
import { SegmentedControl } from 'segmented-control'

Did you hear about this ?

I am suspecting the recent upgrade : https://www.npmjs.com/package/segmented-control/v/0.1.14

Regards,

Pierrot

**Comment by lorensr** [comment]
Thanks for reporting! It should be fixed in `0.1.15`?

**Comment by PierrotGIT** [comment]
I just tried it it's fixed with 0.1.15 version. Thanks ! :)
