### ISSUE TITLE
Add support for CSS loader or CSS modules instead of the existing method

### ISSUE THREAD

**Issue by advance512** [lorensr/segmented-control#6]

**Comment by loan-laux** [comment]
+1, this makes using `segmented-control` on Next.js a pain.

**Comment by loan-laux** [comment]
@advance512 Check out the latest version. It exports `SegmentedControlWithoutStyles` for usage with Next.js. The CSS file simply isn't imported from the plugin, and then it's up to you to import it from your project however you want to.

**Comment by danforejtek** [comment]
`SegmentedControlWithoutStyles` is not working for me 😢

**Comment by loan-laux** [comment]
@danforejtek Can you please provide more details? Any error message? Can you also create a separate issue? Thanks.

**Comment by danforejtek** [comment]
@loan-laux Sure. #42 
Thank you!
