### ISSUE TITLE
onChange event only triggers one time

### ISSUE THREAD

**Issue by Tawpie** [lorensr/segmented-control#8]
Something changed and onChange event only triggers on the first click of a segment. This worked until I update cordova and had npm update all of my modules (many, and I don't know which one triggered the problem). I suspect it's React, see https://github.com/facebook/react/issues/8727

**REPRO:**
_environment:_
react:  react@15.6.1

(!542)-> node --version
v6.9.1

(!543)-> npm --version
4.0.2

(!544)-> cordova --version
7.0.1

(!545)-> cordova platforms ls
Installed platforms:
  android 6.1.2
  ios 4.1.1

make a two segment control
click one segment, onChange fires
click the other segment

**EXPECTED:**

onChange fires

**ACTUAL:**

it doesn't

**NOTES:**

I put in a pull request (and have closed it) that changes the key to use the generated ID, that worked "sometimes" but not always.

EDIT: moving the setValue prop's callback to the label (as onClick) seems to work in my instance. YMMV! 

`{this.props.options.map(option => (
                    <label
                        key={option.value}
                        onClick={() => this.setValue(option.value)}
                        htmlFor={getId(option)}
                        data-value={option.label}
                    >
                        {option.label}
                    </label>
                ))}`

**Comment by jstralko** [comment]
+1 Is it possible to get this change merged into?  Currently, i'm vendoring this code and apply your change.  Would be nice to get this pushed upstream so it benefits all.

**Comment by lorensr** [comment]
Thanks for the fix! Published in `v0.1.8`, lmk if that works 😊

**Comment by jstralko** [comment]
Thank you!
